# src/main/resources/application-test.yml

spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    open-in-view: true

  mail:
    host: localhost
    port: 25
    from: test@example.com #
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

  kafka:
    consumer:
      group-id: test-group
      auto-offset-reset: earliest

event:
  gift-stock-key: "event:gift:stock:test"
  kafka-topic: "event-application-test"

admin:
  secret-key: "test-secret-key"
  header-name: "X-ADMIN-KEY"

jwt:
  secret:
    key: 'dGhpc2lzYW5leGFtcGxlb2Zhc2VjdXJlYW5kcmFuZG9tbHlnZW5lcmF0ZWRzZWNyZXRrZXlmb3Jqd3Q='
  expiration:
    ms: 60000

logging:
  level:
    org.hibernate.SQL: debug

cors:
  allowed-origins: http://localhost:8080
